# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-03 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.RemoveField(
            model_name='business',
            name='image',
        ),
        migrations.RemoveField(
            model_name='business',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
