# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-31 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0004_auto_20190531_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hoodapp.Neighborhood'),
        ),
        migrations.DeleteModel(
            name='neighbourhood',
        ),
    ]
